### ISSUE TITLE
基于新版 DD-WRT 的 musl libc 编译问题及解决

### ISSUE THREAD

**Issue by rampageX** [shadowsocks/ChinaDNS#108]
新版的 DD-WRT 用的 musl libc，用工具链编译 chinadns 出错：

local_ns_parser.c

error: unknown type name 'u_int'

error: unknown type name 'u_char'

原因：
u_int 和 u_char 不是标准的类型

解决，替换 local_ns_parser.c 文件中所有：
u_char 为 unsigned char
u_int 为 unsigned int

**Comment by clowwindy** [comment]
多谢，可以发一个 pull request
