### ISSUE TITLE
Use dnscrypt tcp-mode as chinadns upstream is not support?

### ISSUE THREAD

**Issue by zw963** [shadowsocks/ChinaDNS#134]
I create my own dnscrypt-wrapper server in my vps, it worked.

but seem like UDP is not indeal, so I use tcp-mode only.

in this case, as ChinaDNS upstream, chinadns refuse to work.

```sh
admin@RT-AC5300-5E70:/tmp/mnt/sda1/entware/etc/init.d# dig -p 5356 www.youtube.com
;; Truncated, retrying in TCP mode.
;; Connection to 127.0.0.1#5356(127.0.0.1) for www.youtube.com failed: connection refused.

```

**Comment by s7lx** [comment]
`netstat -anp|grep chinadns`

understand ?
`chinadns`  just  listen on UDP port only
