### ISSUE TITLE
这个项目现在还可以用吗？有没有更好的推荐一下？

### ISSUE THREAD

**Issue by JunShine** [shadowsocks/ChinaDNS#138]
看到最近更新居然是三年前的，感觉有些不安心啊。有没有类似的更好用的项目推荐下？

**Comment by Erich-Chen** [comment]
能用。
追新的话可以看看 [overture](https://github.com/shawn1m/overture)
https://github.com/shawn1m/overture

**Comment by JunShine** [comment]
谢一个哈
